### ISSUE TITLE
Possible multi-threading issue

### ISSUE THREAD

**Issue by YatsenkoVladyslav** [onc-healthit/reference-ccda-validator#106]
### Possible multi-threading issue

![Sequence](https://user-images.githubusercontent.com/85943386/122126491-803f7700-ce3a-11eb-91d5-26ef2865b140.png)

Hi guys, we made a Spring Boot project and we are using your **reference-ccda-validator** project 
which have dependencies on **code-validator-api** and **content-validator-api**.

Our application can accept several requests at the same time and we found two problems with these services:

1. There is a problem with the **org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator** service 
**(reference-ccda-validator)** the problem is in the global variable **GlobalCodeValidatorResults globalCodeValidatorResults**, its state can change in different threads.
https://github.com/onc-healthit/reference-ccda-validator/blob/master/src/main/java/org/sitenv/referenceccda/validators/vocabulary/VocabularyCCDAValidator.java#L29
- State of this variable may change here 
https://github.com/onc-healthit/reference-ccda-validator/blob/master/src/main/java/org/sitenv/referenceccda/validators/vocabulary/VocabularyCCDAValidator.java#L77 

2. There is a problem with the package **org.sitenv.vocabularies.validation.services.VocabularyValidationService** service
**(code-validator-api)** the problem is similar,
https://github.com/onc-healthit/code-validator-api/blob/master/src/main/java/org/sitenv/vocabularies/validation/services/VocabularyValidationService.java#L59
- State of this global variable may change in different threads.
https://github.com/onc-healthit/code-validator-api/blob/master/src/main/java/org/sitenv/vocabularies/validation/services/VocabularyValidationService.java#L207

We have 3 solutions currently on our mind
1. In project **reference-ccda-validator** 
Make the  **org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator** service (with a bean scope Prototype, which will make it possible to always receive a new object inside a different thread, and the state of globalCodeValidatorResults will be the same for the thread that uses it.
In project **code-validator-api**
Do the same for **org.sitenv.vocabularies.validation.services.VocabularyValidationService** service **(code-validator-api)**
-Pull Requests:
(code-validator-api) https://github.com/onc-healthit/code-validator-api/pull/96
(reference-ccda-validator) https://github.com/onc-healthit/reference-ccda-validator/pull/105

2. In project **reference-ccda-validator** 
Wrap GlobalCodeValidatorResults field in **org.sitenv.referenceccda.validators.vocabulary.VocabularyCCDAValidator** service into ThreadLocal and give state to this object via the set method,which will make it possible to make the globalCodeValidatorResults field thread-safe
In project **code-validator-api** do the same for **org.sitenv.vocabularies.validation.services.VocabularyValidationService** service **(code-validator-api)**
-Pull Requests:
(code-validator-api) https://github.com/onc-healthit/code-validator-api/pull/95
(reference-ccda-validator) https://github.com/onc-healthit/reference-ccda-validator/pull/104

3. Rewrite the service methods without global variables, try to do functionality via the local variables inside the methods.

_Two solutions will work right away because we will try to find a solution so as not to break the working functionality since we do not know where else and how this project can work together with other projects_

**Comment by Plow74** [comment]
Thanks for the detailed analysis and providing a solution - the team will certainly look into this.

**Comment by drbgfc** [comment]
Thanks for submitting this - awesome work on the diagram - can't wait to look into it.

**Comment by YatsenkoVladyslav** [comment]
Hi guys, could you please clarify, are there any updates regarding this issue? 
Are we expecting to include it in the nearest releases?

**Comment by Plow74** [comment]
A fix for this will be in the next release.

**Comment by drbgfc** [comment]
Hi,
This fix was released for 3.1.50 SITE release.

Here are the release notes:
V 3.1.50 | Released on: 08/30/2021
C-CDA Sandbox Updates:
C-CDA Validator
Fix DocumentBuilderFactory XXE vulnerability
Fix exception during parallel execution of DocumentBuilder
Update to support HL7 Datatype IVL_REAL as part of new MDHT 20210824 Release
SITE-UI
Fix direct message sender UI sent and received time stamps
Scorecard
Fixed encompassingEncounter efferctiveTime parsing issue
FHIR Sandbox Updates
Added new Patient Data set

The specific ref val release is here, which includes the change. 
https://github.com/onc-healthit/reference-ccda-validator/releases/tag/1.0.59
However, at this point, the latest release is better to use.


@Plow74  @vishalgrp 
Comments from @Plow74  on the fix impl
"I have identified that this is indeed a problem. I'm recommending we bump to the next version of Spring and use the @RequestScope annotation. This implementation does a better job at expressing the intention. I'm going to test this locally.

[08/02/21 8:18 AM](https://oncprojectracking.healthit.gov/support/browse/SITE-3297?focusedCommentId=149901&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-149901)
On DEV - Updated Spring framework and added @RequestScope to the validator beans. The new behavior is not specifically testable, but a regression test is needed due to bumping the Spring framework to a new version.
