### ISSUE TITLE
Question: Are you going to support Java 11?

### ISSUE THREAD

**Issue by OleksandrBrazhnyk** [onc-healthit/reference-ccda-validator#98]
When are you going to add support for Java 11?
What work is required to switch to Java 11?
What if such work would be done by someone else and submitted as a PR or a set of PRs would you review and merge the PRs?

**Comment by drbgfc** [comment]
We haven't looked into what would be needed or planned a date for the upgrade.
We would certainly have to upgrade our tomcat servers.
If someone were to do the work to upgrade the RefVal, ContentVal, and CodeVal to Java 11 (a non-oracle version due to licensing) then I see no reason why we wouldn't look to merge the PRs. I will bring this up at a future meeting though.
Thanks.

**Comment by OleksandrBrazhnyk** [comment]
Thank you for the answers!
